### ISSUE TITLE
Have not been able to launch a game with any version beyond beta4

### ISSUE THREAD

**Issue by Saereth** [PickAID/Champions#54]
#### Versions (Be specific, do not write "latest"):
* Champions: champions-neoforge-1.21.1-2.1.8.4-hotfix-2
* NeoForge: 21.1.80

#### Observed Behavior:
- The game will hang anytime you try to load it with a version of champions beyond beta4. The latest.log clearly shows the hang and then crash in regards to the configs
- I have deleted all champions configs and defaultconfigs to let them regenerate

#### Expected Behavior:
- For the world to load as normal
- 
#### Steps to Reproduce:
1. Update to version 2.1.8.4-hotfix-2
2. Delete existing configs for champions
3. World no longer loads

Latest Log: https://mclo.gs/QR3yBdd
Crash Log: https://mclo.gs/PxpYybO

**Comment by Hypocisy** [comment]
It seems you are not deleted all champions config and defaultconfigs, could you try to install champion with fresh neoforge version?
this is what i get when debuging, it works fine.
![image](https://github.com/user-attachments/assets/6ea343e4-3736-4c36-957d-0a2664819049)
this is your crashes, it shows defaultColor=16777215, witch is not currect, because it should be hex fomat
![image](https://github.com/user-attachments/assets/4f7e7952-9465-4d61-b839-157650c9beab)

**Comment by Saereth** [comment]
ok so I deleted them again and it still didnt work so I tried something different, I deleted them and then created a new world. This worked and the configs repopulated correctly. I was then able to go out and open my existing world just fine so I guess this is sorted now, just weird. Thanks for the response!

**Comment by Hypocisy** [comment]
> ok so I deleted them again and it still didnt work so I tried something different, I deleted them and then created a new world. This worked and the configs repopulated correctly. I was then able to go out and open my existing world just fine so I guess this is sorted now, just weird. Thanks for the response!

great!
